// AUTOGENERIERT von scripts/generate-data.py – bitte nicht von Hand editieren.
// Quelle: Typeform-Einsendungen „40 Jahre UNIO“ (2019),
// Jubiläumskonzert 21.11.2019 im Brucknerhaus Linz.

export const MOTIFS = [
  {
    "key": "gnom",
    "title": "Der Gnom",
    "subtitle": "Gnomus",
    "color": "#E4572E"
  },
  {
    "key": "schloss",
    "title": "Das alte Schloss",
    "subtitle": "Il vecchio castello",
    "color": "#3F8E6E"
  },
  {
    "key": "tuilerien",
    "title": "Die Tuilerien",
    "subtitle": "Spielende Kinder im Streit",
    "color": "#E8A13A"
  },
  {
    "key": "ochsenkarren",
    "title": "Der Ochsenkarren",
    "subtitle": "Bydło",
    "color": "#9A6B3F"
  },
  {
    "key": "kuechlein",
    "title": "Ballett der Küchlein",
    "subtitle": "in ihren Eierschalen",
    "color": "#EBC34B"
  },
  {
    "key": "limoges",
    "title": "Limoges. Der Marktplatz",
    "subtitle": "Die große Neuigkeit",
    "color": "#DD7FA6"
  },
  {
    "key": "katakomben",
    "title": "Die Katakomben",
    "subtitle": "Römische Gruft",
    "color": "#5B6C8F"
  },
  {
    "key": "tote-sprache",
    "title": "Mit den Toten in einer toten Sprache",
    "subtitle": "Cum mortuis in lingua mortua",
    "color": "#6E6678"
  },
  {
    "key": "baba-jaga",
    "title": "Die Hütte der Baba-Jaga",
    "subtitle": "Die Hütte auf Hühnerfüßen",
    "color": "#7B4B94"
  },
  {
    "key": "tor-von-kiew",
    "title": "Das große Tor von Kiew",
    "subtitle": "Das Heldentor in der alten Hauptstadt",
    "color": "#C2412F"
  }
];

export const WORKS = [
  {
    "id": 1,
    "slug": "maria-wallner-tor-von-kiew",
    "name": "Maria Wallner",
    "vorname": "Maria",
    "nachname": "Wallner",
    "jahr": 1959,
    "motif": "tor-von-kiew",
    "motifTitle": "Das große Tor von Kiew",
    "technik": "Collage",
    "titel": "Livemusik in Kiew",
    "file": "75392727_809950276104673_358034916245504000_n.jpg",
    "image": "/werke/maria-wallner-tor-von-kiew.jpg"
  },
  {
    "id": 2,
    "slug": "caroline-schiller-baba-jaga",
    "name": "Caroline Schiller",
    "vorname": "Caroline",
    "nachname": "Schiller",
    "jahr": 2011,
    "motif": "baba-jaga",
    "motifTitle": "Die Hütte der Baba-Jaga",
    "technik": "Farbstifte",
    "titel": "Hexenhaus",
    "file": "76232071_2427512944182684_8808104374992633856_n.jpg",
    "image": "/werke/caroline-schiller-baba-jaga.jpg"
  },
  {
    "id": 3,
    "slug": "valentina-stelzhammer-schloss",
    "name": "Valentina Stelzhammer",
    "vorname": "Valentina",
    "nachname": "Stelzhammer",
    "jahr": 2009,
    "motif": "schloss",
    "motifTitle": "Das alte Schloss",
    "technik": "Farbstifte",
    "titel": "Mein Traumschloss",
    "file": "78124200_792765194506448_8992540874957127680_n.jpg",
    "image": "/werke/valentina-stelzhammer-schloss.jpg"
  },
  {
    "id": 4,
    "slug": "jana-lenglachner-schloss",
    "name": "Jana Lenglachner",
    "vorname": "Jana",
    "nachname": "Lenglachner",
    "jahr": 2012,
    "motif": "schloss",
    "motifTitle": "Das alte Schloss",
    "technik": "Farbstifte",
    "titel": "Ein Schloss in meiner Nähe",
    "file": "73523458_576362832935694_8433799237866618880_n.jpg",
    "image": "/werke/jana-lenglachner-schloss.jpg"
  },
  {
    "id": 5,
    "slug": "valentina-stelzhammer-schloss-2",
    "name": "Valentina Stelzhammer",
    "vorname": "Valentina",
    "nachname": "Stelzhammer",
    "jahr": 2009,
    "motif": "schloss",
    "motifTitle": "Das alte Schloss",
    "technik": "Farbstifte",
    "titel": "Mein Traumschloss",
    "file": "73523458_576362832935694_8433799237866618880_n.jpg",
    "image": "/werke/valentina-stelzhammer-schloss-2.jpg"
  },
  {
    "id": 6,
    "slug": "iris-brandstetter-schloss",
    "name": "Iris Brandstetter",
    "vorname": "Iris",
    "nachname": "Brandstetter",
    "jahr": 2007,
    "motif": "schloss",
    "motifTitle": "Das alte Schloss",
    "technik": "Bleistift",
    "titel": "",
    "file": "Das_alte_Schloss.jpg",
    "image": "/werke/iris-brandstetter-schloss.jpg"
  },
  {
    "id": 7,
    "slug": "kerstin-schmollmueller-schloss",
    "name": "Kerstin Schmollmüller",
    "vorname": "Kerstin",
    "nachname": "Schmollmüller",
    "jahr": 1976,
    "motif": "schloss",
    "motifTitle": "Das alte Schloss",
    "technik": "Aquarell",
    "titel": "",
    "file": "Das_alte_Schloß_2.jpg",
    "image": "/werke/kerstin-schmollmueller-schloss.jpg"
  },
  {
    "id": 8,
    "slug": "debora-hufnagel-tor-von-kiew",
    "name": "Debora Hufnagel",
    "vorname": "Debora",
    "nachname": "Hufnagel",
    "jahr": 2008,
    "motif": "tor-von-kiew",
    "motifTitle": "Das große Tor von Kiew",
    "technik": "Farbstifte",
    "titel": "",
    "file": "3731_001.jpg",
    "image": "/werke/debora-hufnagel-tor-von-kiew.jpg"
  },
  {
    "id": 9,
    "slug": "valentin-malicky-baba-jaga",
    "name": "Valentin Malicky",
    "vorname": "Valentin",
    "nachname": "Malicky",
    "jahr": 2008,
    "motif": "baba-jaga",
    "motifTitle": "Die Hütte der Baba-Jaga",
    "technik": "Buntstifte",
    "titel": "Baba Jaga",
    "file": "15735738003421672918895796894456.jpg",
    "image": "/werke/valentin-malicky-baba-jaga.jpg"
  },
  {
    "id": 10,
    "slug": "fridolin-malicky-tor-von-kiew",
    "name": "Fridolin Malicky",
    "vorname": "Fridolin",
    "nachname": "Malicky",
    "jahr": 2005,
    "motif": "tor-von-kiew",
    "motifTitle": "Das große Tor von Kiew",
    "technik": "Bleistift",
    "titel": "Das Tor zu Kiew",
    "file": "15735735205164486727015421004124.jpg",
    "image": "/werke/fridolin-malicky-tor-von-kiew.jpg"
  },
  {
    "id": 11,
    "slug": "klavierschueler-der-lms-schwanenstadt-baba-jaga",
    "name": "Klavierschüler Der LMS Schwanenstadt",
    "vorname": "Klavierschüler",
    "nachname": "Der LMS Schwanenstadt",
    "jahr": 2009,
    "motif": "baba-jaga",
    "motifTitle": "Die Hütte der Baba-Jaga",
    "technik": "Farbstifte",
    "titel": "Baumhäuser",
    "file": "Baumhäuser.jpg",
    "image": "/werke/klavierschueler-der-lms-schwanenstadt-baba-jaga.jpg"
  },
  {
    "id": 12,
    "slug": "klavierschueler-der-lms-schwanenstadt-schloss",
    "name": "Klavierschüler Der LMS Schwanenstadt",
    "vorname": "Klavierschüler",
    "nachname": "Der LMS Schwanenstadt",
    "jahr": 2009,
    "motif": "schloss",
    "motifTitle": "Das alte Schloss",
    "technik": "Farbstifte",
    "titel": "Schlösser am Rand der Donaustadt Linz",
    "file": "Schlösser_am_Rand_der_Donaustadt_Linz.jpg",
    "image": "/werke/klavierschueler-der-lms-schwanenstadt-schloss.jpg"
  },
  {
    "id": 13,
    "slug": "johanna-siller-gnom",
    "name": "Johanna Siller",
    "vorname": "Johanna",
    "nachname": "Siller",
    "jahr": 2011,
    "motif": "gnom",
    "motifTitle": "Der Gnom",
    "technik": "Farbstifte",
    "titel": "Der Gnom",
    "file": "Gnom_JohannaSiller_1.bmp",
    "image": "/werke/johanna-siller-gnom.jpg"
  },
  {
    "id": 14,
    "slug": "johanna-siller-baba-jaga",
    "name": "Johanna Siller",
    "vorname": "Johanna",
    "nachname": "Siller",
    "jahr": 2011,
    "motif": "baba-jaga",
    "motifTitle": "Die Hütte der Baba-Jaga",
    "technik": "Farbstifte",
    "titel": "Hütte auf Hühnerfüßen",
    "file": "Huette_JohannaSiller_3.bmp",
    "image": "/werke/johanna-siller-baba-jaga.jpg"
  },
  {
    "id": 15,
    "slug": "theresa-siller-gnom",
    "name": "Theresa Siller",
    "vorname": "Theresa",
    "nachname": "Siller",
    "jahr": 2017,
    "motif": "gnom",
    "motifTitle": "Der Gnom",
    "technik": "Filzstifte",
    "titel": "Der Gnom",
    "file": "Gnom_TheresaSiller_1.bmp",
    "image": "/werke/theresa-siller-gnom.jpg"
  },
  {
    "id": 16,
    "slug": "magdalena-siller-baba-jaga",
    "name": "Magdalena Siller",
    "vorname": "Magdalena",
    "nachname": "Siller",
    "jahr": 2008,
    "motif": "baba-jaga",
    "motifTitle": "Die Hütte der Baba-Jaga",
    "technik": "Buntstifte",
    "titel": "Hütte auf Hühnerfüßen",
    "file": "Huette_MagdalenaSiller_1.bmp",
    "image": "/werke/magdalena-siller-baba-jaga.jpg"
  },
  {
    "id": 17,
    "slug": "maria-wallner-schloss",
    "name": "Maria Wallner",
    "vorname": "Maria",
    "nachname": "Wallner",
    "jahr": 1959,
    "motif": "schloss",
    "motifTitle": "Das alte Schloss",
    "technik": "Collage",
    "titel": "Das alte Schloss",
    "file": "Das_alte_Schloss.jpg",
    "image": "/werke/maria-wallner-schloss.jpg"
  },
  {
    "id": 18,
    "slug": "verena-renner-tuilerien",
    "name": "Verena Renner",
    "vorname": "Verena",
    "nachname": "Renner",
    "jahr": 1993,
    "motif": "tuilerien",
    "motifTitle": "Die Tuilerien",
    "technik": "Collage",
    "titel": "",
    "file": "IMG_0461.JPG",
    "image": "/werke/verena-renner-tuilerien.jpg"
  },
  {
    "id": 19,
    "slug": "verena-renner-tuilerien-2",
    "name": "Verena Renner",
    "vorname": "Verena",
    "nachname": "Renner",
    "jahr": 1993,
    "motif": "tuilerien",
    "motifTitle": "Die Tuilerien",
    "technik": "Linolschnitt-Druck mit Acrylfarbe",
    "titel": "",
    "file": "27F616F3_819A_410D_9F94_7C6742078A6B.jpg",
    "image": "/werke/verena-renner-tuilerien-2.jpg"
  },
  {
    "id": 20,
    "slug": "verena-renner-tuilerien-3",
    "name": "Verena Renner",
    "vorname": "Verena",
    "nachname": "Renner",
    "jahr": 1993,
    "motif": "tuilerien",
    "motifTitle": "Die Tuilerien",
    "technik": "Linolschnitt-Druck mit Acrylfarbe",
    "titel": "",
    "file": "370EDEC8_25D1_4618_A63E_F2F1E1CFBBE5.jpg",
    "image": "/werke/verena-renner-tuilerien-3.jpg"
  },
  {
    "id": 21,
    "slug": "verena-renner-tuilerien-4",
    "name": "Verena Renner",
    "vorname": "Verena",
    "nachname": "Renner",
    "jahr": 1993,
    "motif": "tuilerien",
    "motifTitle": "Die Tuilerien",
    "technik": "Tusche und Acryl auf Holzplatte",
    "titel": "",
    "file": "IMG_3947.PNG",
    "image": "/werke/verena-renner-tuilerien-4.jpg"
  },
  {
    "id": 22,
    "slug": "verena-renner-tuilerien-5",
    "name": "Verena Renner",
    "vorname": "Verena",
    "nachname": "Renner",
    "jahr": 1993,
    "motif": "tuilerien",
    "motifTitle": "Die Tuilerien",
    "technik": "Acryl auf Leinwand mit Notenblättern",
    "titel": "",
    "file": "IMG_3946.PNG",
    "image": "/werke/verena-renner-tuilerien-5.jpg"
  },
  {
    "id": 23,
    "slug": "paula-haslinger-gnom",
    "name": "Paula Haslinger",
    "vorname": "Paula",
    "nachname": "Haslinger",
    "jahr": 2005,
    "motif": "gnom",
    "motifTitle": "Der Gnom",
    "technik": "Bleistift",
    "titel": "",
    "file": "Paula_Haslinger_2005.JPG",
    "image": "/werke/paula-haslinger-gnom.jpg"
  },
  {
    "id": 24,
    "slug": "anja-riegler-gnom",
    "name": "Anja Riegler",
    "vorname": "Anja",
    "nachname": "Riegler",
    "jahr": 2005,
    "motif": "gnom",
    "motifTitle": "Der Gnom",
    "technik": "Bleistift",
    "titel": "",
    "file": "Anja_Riegler_2005.JPG",
    "image": "/werke/anja-riegler-gnom.jpg"
  },
  {
    "id": 25,
    "slug": "sebastian-langegger-gnom",
    "name": "Sebastian Langegger",
    "vorname": "Sebastian",
    "nachname": "Langegger",
    "jahr": 2007,
    "motif": "gnom",
    "motifTitle": "Der Gnom",
    "technik": "Deckfarben",
    "titel": "",
    "file": "Sebastian_Langegger_2007.JPG",
    "image": "/werke/sebastian-langegger-gnom.jpg"
  },
  {
    "id": 26,
    "slug": "rafael-viertlmayr-gnom",
    "name": "Rafael Viertlmayr",
    "vorname": "Rafael",
    "nachname": "Viertlmayr",
    "jahr": 2008,
    "motif": "gnom",
    "motifTitle": "Der Gnom",
    "technik": "Aquarell",
    "titel": "",
    "file": "Rafael_Viertlmayr_2008.JPG",
    "image": "/werke/rafael-viertlmayr-gnom.jpg"
  },
  {
    "id": 27,
    "slug": "veronika-sigl-gnom",
    "name": "Veronika Sigl",
    "vorname": "Veronika",
    "nachname": "Sigl",
    "jahr": 2008,
    "motif": "gnom",
    "motifTitle": "Der Gnom",
    "technik": "Deckfarben",
    "titel": "",
    "file": "Veronika_Siegl_2008.JPG",
    "image": "/werke/veronika-sigl-gnom.jpg"
  },
  {
    "id": 28,
    "slug": "selina-stegfellner-gnom",
    "name": "Selina Stegfellner",
    "vorname": "Selina",
    "nachname": "Stegfellner",
    "jahr": 2008,
    "motif": "gnom",
    "motifTitle": "Der Gnom",
    "technik": "Deckfarben",
    "titel": "",
    "file": "Stegfellner_Selina_2007.JPG",
    "image": "/werke/selina-stegfellner-gnom.jpg"
  },
  {
    "id": 29,
    "slug": "leonhard-grandl-baba-jaga",
    "name": "Leonhard Grandl",
    "vorname": "Leonhard",
    "nachname": "Grandl",
    "jahr": 2007,
    "motif": "baba-jaga",
    "motifTitle": "Die Hütte der Baba-Jaga",
    "technik": "Deckfarben",
    "titel": "",
    "file": "Leonhard_Grandl_2007.JPG",
    "image": "/werke/leonhard-grandl-baba-jaga.jpg"
  },
  {
    "id": 30,
    "slug": "viktorie-raabova-ochsenkarren",
    "name": "Viktorie Raabova",
    "vorname": "Viktorie",
    "nachname": "Raabova",
    "jahr": 2001,
    "motif": "ochsenkarren",
    "motifTitle": "Der Ochsenkarren",
    "technik": "Wasserfarben",
    "titel": "",
    "file": "Ochsenkarren_v.jpg",
    "image": "/werke/viktorie-raabova-ochsenkarren.jpg"
  },
  {
    "id": 31,
    "slug": "magdalena-honeder-baba-jaga",
    "name": "Magdalena Honeder",
    "vorname": "Magdalena",
    "nachname": "Honeder",
    "jahr": 2007,
    "motif": "baba-jaga",
    "motifTitle": "Die Hütte der Baba-Jaga",
    "technik": "Deckfarben",
    "titel": "",
    "file": "Magdalena_Honeder_2007.JPG",
    "image": "/werke/magdalena-honeder-baba-jaga.jpg"
  },
  {
    "id": 32,
    "slug": "rolf-conrath-tor-von-kiew",
    "name": "Rolf Conrath",
    "vorname": "Rolf",
    "nachname": "Conrath",
    "jahr": 1942,
    "motif": "tor-von-kiew",
    "motifTitle": "Das große Tor von Kiew",
    "technik": "Filzstifte",
    "titel": "",
    "file": "Tor.jpg",
    "image": "/werke/rolf-conrath-tor-von-kiew.jpg"
  },
  {
    "id": 33,
    "slug": "lisa-langthaler-baba-jaga",
    "name": "Lisa Langthaler",
    "vorname": "Lisa",
    "nachname": "Langthaler",
    "jahr": 2007,
    "motif": "baba-jaga",
    "motifTitle": "Die Hütte der Baba-Jaga",
    "technik": "Deckfarben",
    "titel": "",
    "file": "Lisa_Langthaler_2007.JPG",
    "image": "/werke/lisa-langthaler-baba-jaga.jpg"
  },
  {
    "id": 34,
    "slug": "josef-brandner-schloss",
    "name": "Josef Brandner",
    "vorname": "Josef",
    "nachname": "Brandner",
    "jahr": 2004,
    "motif": "schloss",
    "motifTitle": "Das alte Schloss",
    "technik": "Wasserfarben",
    "titel": "",
    "file": "Altes_Schloss_J.jpg",
    "image": "/werke/josef-brandner-schloss.jpg"
  },
  {
    "id": 35,
    "slug": "magdalena-gusenbauer-baba-jaga",
    "name": "Magdalena Gusenbauer",
    "vorname": "Magdalena",
    "nachname": "Gusenbauer",
    "jahr": 2007,
    "motif": "baba-jaga",
    "motifTitle": "Die Hütte der Baba-Jaga",
    "technik": "Deckfarben",
    "titel": "",
    "file": "Magdalena_Gusenbauer_2007.JPG",
    "image": "/werke/magdalena-gusenbauer-baba-jaga.jpg"
  },
  {
    "id": 36,
    "slug": "jakob-brandner-gnom",
    "name": "Jakob Brandner",
    "vorname": "Jakob",
    "nachname": "Brandner",
    "jahr": 2010,
    "motif": "gnom",
    "motifTitle": "Der Gnom",
    "technik": "Wasserfarben",
    "titel": "",
    "file": "Gnomus_j.jpg",
    "image": "/werke/jakob-brandner-gnom.jpg"
  },
  {
    "id": 37,
    "slug": "katharina-peirleitner-gnom",
    "name": "Katharina Peirleitner",
    "vorname": "Katharina",
    "nachname": "Peirleitner",
    "jahr": 2006,
    "motif": "gnom",
    "motifTitle": "Der Gnom",
    "technik": "Deckfarben",
    "titel": "",
    "file": "Katharina_Peirleitner_2006.JPG",
    "image": "/werke/katharina-peirleitner-gnom.jpg"
  },
  {
    "id": 38,
    "slug": "rolf-conrath-tuilerien",
    "name": "Rolf Conrath",
    "vorname": "Rolf",
    "nachname": "Conrath",
    "jahr": 1942,
    "motif": "tuilerien",
    "motifTitle": "Die Tuilerien",
    "technik": "Filzstifte",
    "titel": "",
    "file": "Tulerien_1.jpg",
    "image": "/werke/rolf-conrath-tuilerien.jpg"
  },
  {
    "id": 39,
    "slug": "vanessa-schmalzer-gnom",
    "name": "Vanessa Schmalzer",
    "vorname": "Vanessa",
    "nachname": "Schmalzer",
    "jahr": 2006,
    "motif": "gnom",
    "motifTitle": "Der Gnom",
    "technik": "Deckfarben",
    "titel": "",
    "file": "Vanessa_Schmalzer_2006.JPG",
    "image": "/werke/vanessa-schmalzer-gnom.jpg"
  },
  {
    "id": 40,
    "slug": "monja-zehethofer-gnom",
    "name": "Monja Zehethofer",
    "vorname": "Monja",
    "nachname": "Zehethofer",
    "jahr": 2006,
    "motif": "gnom",
    "motifTitle": "Der Gnom",
    "technik": "Farbstifte",
    "titel": "",
    "file": "Monja_Zehethofer.JPG",
    "image": "/werke/monja-zehethofer-gnom.jpg"
  },
  {
    "id": 41,
    "slug": "rolf-conrath-ochsenkarren",
    "name": "Rolf Conrath",
    "vorname": "Rolf",
    "nachname": "Conrath",
    "jahr": 1942,
    "motif": "ochsenkarren",
    "motifTitle": "Der Ochsenkarren",
    "technik": "Filzstifte",
    "titel": "",
    "file": "Ochsenkarren_1.jpg",
    "image": "/werke/rolf-conrath-ochsenkarren.jpg"
  },
  {
    "id": 42,
    "slug": "rolf-conrath-schloss",
    "name": "Rolf Conrath",
    "vorname": "Rolf",
    "nachname": "Conrath",
    "jahr": 1942,
    "motif": "schloss",
    "motifTitle": "Das alte Schloss",
    "technik": "Filzstifte",
    "titel": "",
    "file": "Altes_Schloss.JPG",
    "image": "/werke/rolf-conrath-schloss.jpg"
  },
  {
    "id": 43,
    "slug": "arthur-zangl-schloss",
    "name": "Arthur Zangl",
    "vorname": "Arthur",
    "nachname": "Zangl",
    "jahr": 2004,
    "motif": "schloss",
    "motifTitle": "Das alte Schloss",
    "technik": "Farbstifte",
    "titel": "",
    "file": "Arthur_Zangl_2004.JPG",
    "image": "/werke/arthur-zangl-schloss.jpg"
  },
  {
    "id": 44,
    "slug": "rolf-conrath-gnom",
    "name": "Rolf Conrath",
    "vorname": "Rolf",
    "nachname": "Conrath",
    "jahr": 1942,
    "motif": "gnom",
    "motifTitle": "Der Gnom",
    "technik": "Filzstifte",
    "titel": "",
    "file": "Gnomus.jpg",
    "image": "/werke/rolf-conrath-gnom.jpg"
  },
  {
    "id": 45,
    "slug": "alina-wolfinger-baba-jaga",
    "name": "Alina Wolfinger",
    "vorname": "Alina",
    "nachname": "Wolfinger",
    "jahr": 2008,
    "motif": "baba-jaga",
    "motifTitle": "Die Hütte der Baba-Jaga",
    "technik": "Aquarell",
    "titel": "",
    "file": "Alina_Wolfinger_Bodendorf_182_4223_Katsdorf__2008.JPG",
    "image": "/werke/alina-wolfinger-baba-jaga.jpg"
  },
  {
    "id": 46,
    "slug": "xandria-furchtlehner-tuilerien",
    "name": "Xandria Furchtlehner",
    "vorname": "Xandria",
    "nachname": "Furchtlehner",
    "jahr": 2006,
    "motif": "tuilerien",
    "motifTitle": "Die Tuilerien",
    "technik": "Farbstifte",
    "titel": "Der Streit um das kaputte Boot",
    "file": "Xandria_Furchtlehner_2006.JPG",
    "image": "/werke/xandria-furchtlehner-tuilerien.jpg"
  },
  {
    "id": 47,
    "slug": "sarah-lengauer-tuilerien",
    "name": "Sarah Lengauer",
    "vorname": "Sarah",
    "nachname": "Lengauer",
    "jahr": 2007,
    "motif": "tuilerien",
    "motifTitle": "Die Tuilerien",
    "technik": "Farbstifte",
    "titel": "",
    "file": "Sarah_Lengauer_2007.JPG",
    "image": "/werke/sarah-lengauer-tuilerien.jpg"
  },
  {
    "id": 48,
    "slug": "tina-hoellmueller-gnom",
    "name": "Tina Höllmüller",
    "vorname": "Tina",
    "nachname": "Höllmüller",
    "jahr": 2006,
    "motif": "gnom",
    "motifTitle": "Der Gnom",
    "technik": "Deckfarben",
    "titel": "",
    "file": "Tina_Höllmüller_2006.JPG",
    "image": "/werke/tina-hoellmueller-gnom.jpg"
  },
  {
    "id": 49,
    "slug": "sebastian-tichler-baba-jaga",
    "name": "Sebastian Tichler",
    "vorname": "Sebastian",
    "nachname": "Tichler",
    "jahr": 2005,
    "motif": "baba-jaga",
    "motifTitle": "Die Hütte der Baba-Jaga",
    "technik": "Deckfarben",
    "titel": "",
    "file": "Sebastian_Tichler_2005.JPG",
    "image": "/werke/sebastian-tichler-baba-jaga.jpg"
  },
  {
    "id": 50,
    "slug": "sophia-schatz-baba-jaga",
    "name": "Sophia Schatz",
    "vorname": "Sophia",
    "nachname": "Schatz",
    "jahr": 2008,
    "motif": "baba-jaga",
    "motifTitle": "Die Hütte der Baba-Jaga",
    "technik": "Deckfarben",
    "titel": "",
    "file": "Sophia_Schatz2008.JPG",
    "image": "/werke/sophia-schatz-baba-jaga.jpg"
  },
  {
    "id": 51,
    "slug": "sebastian-roeschel-baba-jaga",
    "name": "Sebastian Röschel",
    "vorname": "Sebastian",
    "nachname": "Röschel",
    "jahr": 2005,
    "motif": "baba-jaga",
    "motifTitle": "Die Hütte der Baba-Jaga",
    "technik": "Filzstifte",
    "titel": "",
    "file": "Sebastian_Röschel.JPG",
    "image": "/werke/sebastian-roeschel-baba-jaga.jpg"
  },
  {
    "id": 52,
    "slug": "samuel-hackl-baba-jaga",
    "name": "Samuel Hackl",
    "vorname": "Samuel",
    "nachname": "Hackl",
    "jahr": 2005,
    "motif": "baba-jaga",
    "motifTitle": "Die Hütte der Baba-Jaga",
    "technik": "Farbstift",
    "titel": "",
    "file": "Hackl_Samuel_2005.JPG",
    "image": "/werke/samuel-hackl-baba-jaga.jpg"
  },
  {
    "id": 53,
    "slug": "patrick-pamminger-baba-jaga",
    "name": "Patrick Pamminger",
    "vorname": "Patrick",
    "nachname": "Pamminger",
    "jahr": 2006,
    "motif": "baba-jaga",
    "motifTitle": "Die Hütte der Baba-Jaga",
    "technik": "Bleistiftzeichnung",
    "titel": "",
    "file": "Patrick_Pamminger_2006.JPG",
    "image": "/werke/patrick-pamminger-baba-jaga.jpg"
  },
  {
    "id": 54,
    "slug": "theresa-schinnerl-gnom",
    "name": "Theresa Schinnerl",
    "vorname": "Theresa",
    "nachname": "Schinnerl",
    "jahr": 2006,
    "motif": "gnom",
    "motifTitle": "Der Gnom",
    "technik": "Bleistiftzeichnung",
    "titel": "",
    "file": "Theresa_Schinnerl_2006.JPG",
    "image": "/werke/theresa-schinnerl-gnom.jpg"
  },
  {
    "id": 55,
    "slug": "tina-hoellmueller-gnom-2",
    "name": "Tina Höllmüller",
    "vorname": "Tina",
    "nachname": "Höllmüller",
    "jahr": 2006,
    "motif": "gnom",
    "motifTitle": "Der Gnom",
    "technik": "Deckfarben",
    "titel": "",
    "file": "Tina_Höllmüller_2006.JPG",
    "image": "/werke/tina-hoellmueller-gnom-2.jpg"
  },
  {
    "id": 56,
    "slug": "jana-mueckstein-gnom",
    "name": "Jana Mückstein",
    "vorname": "Jana",
    "nachname": "Mückstein",
    "jahr": 2006,
    "motif": "gnom",
    "motifTitle": "Der Gnom",
    "technik": "Deckfarben",
    "titel": "",
    "file": "Jana_Mückstein_2006.JPG",
    "image": "/werke/jana-mueckstein-gnom.jpg"
  },
  {
    "id": 57,
    "slug": "felix-hoellwirth-schloss",
    "name": "Felix Höllwirth",
    "vorname": "Felix",
    "nachname": "Höllwirth",
    "jahr": 2006,
    "motif": "schloss",
    "motifTitle": "Das alte Schloss",
    "technik": "Farbstifte",
    "titel": "",
    "file": "Felix_Höllwirth_2006.JPG",
    "image": "/werke/felix-hoellwirth-schloss.jpg"
  },
  {
    "id": 58,
    "slug": "lena-fetzer-schloss",
    "name": "Lena Fetzer",
    "vorname": "Lena",
    "nachname": "Fetzer",
    "jahr": 2005,
    "motif": "schloss",
    "motifTitle": "Das alte Schloss",
    "technik": "Farbstifte",
    "titel": "",
    "file": "Lena_Fetzer_2005.JPG",
    "image": "/werke/lena-fetzer-schloss.jpg"
  },
  {
    "id": 59,
    "slug": "marvin-pils-baba-jaga",
    "name": "Marvin Pils",
    "vorname": "Marvin",
    "nachname": "Pils",
    "jahr": 2006,
    "motif": "baba-jaga",
    "motifTitle": "Die Hütte der Baba-Jaga",
    "technik": "Farbstifte",
    "titel": "",
    "file": "Marvin_Pils_2006.JPG",
    "image": "/werke/marvin-pils-baba-jaga.jpg"
  },
  {
    "id": 60,
    "slug": "daniel-feichtner-baba-jaga",
    "name": "Daniel Feichtner",
    "vorname": "Daniel",
    "nachname": "Feichtner",
    "jahr": 2006,
    "motif": "baba-jaga",
    "motifTitle": "Die Hütte der Baba-Jaga",
    "technik": "Farbstifte",
    "titel": "",
    "file": "Daniel_Feichtner_2006.JPG",
    "image": "/werke/daniel-feichtner-baba-jaga.jpg"
  },
  {
    "id": 61,
    "slug": "fabian-roebl-baba-jaga",
    "name": "Fabian Röbl",
    "vorname": "Fabian",
    "nachname": "Röbl",
    "jahr": 2006,
    "motif": "baba-jaga",
    "motifTitle": "Die Hütte der Baba-Jaga",
    "technik": "Farbstifte",
    "titel": "Hexenhaus",
    "file": "Fabian_Röbl_2006.JPG",
    "image": "/werke/fabian-roebl-baba-jaga.jpg"
  },
  {
    "id": 62,
    "slug": "leonie-aistleitner-gnom",
    "name": "Leonie Aistleitner",
    "vorname": "Leonie",
    "nachname": "Aistleitner",
    "jahr": 2008,
    "motif": "gnom",
    "motifTitle": "Der Gnom",
    "technik": "Aquarell und Farbstifte",
    "titel": "Der Gnom",
    "file": "Gnom__Leonie_Aistleitner_Standorf_2_4223_Katsdorf_2008.jpg",
    "image": "/werke/leonie-aistleitner-gnom.jpg"
  },
  {
    "id": 63,
    "slug": "sarah-poltschak-baba-jaga",
    "name": "Sarah Poltschak",
    "vorname": "Sarah",
    "nachname": "Poltschak",
    "jahr": 2013,
    "motif": "baba-jaga",
    "motifTitle": "Die Hütte der Baba-Jaga",
    "technik": "Buntstift auf Papier",
    "titel": "Haus auf Hühnerfüßen",
    "file": "Haus_auf_Hühnerfuessen.pdf",
    "image": "/werke/sarah-poltschak-baba-jaga.jpg"
  },
  {
    "id": 64,
    "slug": "emily-radner-tuilerien",
    "name": "Emily Radner",
    "vorname": "Emily",
    "nachname": "Radner",
    "jahr": 2010,
    "motif": "tuilerien",
    "motifTitle": "Die Tuilerien",
    "technik": "Farbstift",
    "titel": "",
    "file": "Radner_Emily_Tuileries.pdf",
    "image": "/werke/emily-radner-tuilerien.jpg"
  },
  {
    "id": 65,
    "slug": "emily-radner-schloss",
    "name": "Emily Radner",
    "vorname": "Emily",
    "nachname": "Radner",
    "jahr": 2010,
    "motif": "schloss",
    "motifTitle": "Das alte Schloss",
    "technik": "Farbstift",
    "titel": "",
    "file": "Radner_Emily_Schloss.pdf",
    "image": "/werke/emily-radner-schloss.jpg"
  },
  {
    "id": 66,
    "slug": "emily-radner-tor-von-kiew",
    "name": "Emily Radner",
    "vorname": "Emily",
    "nachname": "Radner",
    "jahr": 2010,
    "motif": "tor-von-kiew",
    "motifTitle": "Das große Tor von Kiew",
    "technik": "Farbstift",
    "titel": "",
    "file": "Radner_Emily_gr._Tor.pdf",
    "image": "/werke/emily-radner-tor-von-kiew.jpg"
  },
  {
    "id": 67,
    "slug": "emily-radner-gnom",
    "name": "Emily Radner",
    "vorname": "Emily",
    "nachname": "Radner",
    "jahr": 2010,
    "motif": "gnom",
    "motifTitle": "Der Gnom",
    "technik": "Farbstift",
    "titel": "",
    "file": "Radner_Emily_Der_Gnom.pdf",
    "image": "/werke/emily-radner-gnom.jpg"
  },
  {
    "id": 68,
    "slug": "emily-radner-ochsenkarren",
    "name": "Emily Radner",
    "vorname": "Emily",
    "nachname": "Radner",
    "jahr": 2010,
    "motif": "ochsenkarren",
    "motifTitle": "Der Ochsenkarren",
    "technik": "Farbstift",
    "titel": "",
    "file": "Radner_Emily_Bydlo.pdf",
    "image": "/werke/emily-radner-ochsenkarren.jpg"
  },
  {
    "id": 69,
    "slug": "anton-niedermayr-baba-jaga",
    "name": "Anton Niedermayr",
    "vorname": "Anton",
    "nachname": "Niedermayr",
    "jahr": 2007,
    "motif": "baba-jaga",
    "motifTitle": "Die Hütte der Baba-Jaga",
    "technik": "Farbstift",
    "titel": "",
    "file": "Anton_Niedermayr.pdf",
    "image": "/werke/anton-niedermayr-baba-jaga.jpg"
  },
  {
    "id": 70,
    "slug": "daniel-kurz-reichmann-gnom",
    "name": "Daniel Kurz-Reichmann",
    "vorname": "Daniel",
    "nachname": "Kurz-Reichmann",
    "jahr": 2008,
    "motif": "gnom",
    "motifTitle": "Der Gnom",
    "technik": "Farbstift",
    "titel": "",
    "file": "Daniel_Kurz_Reichmann.pdf",
    "image": "/werke/daniel-kurz-reichmann-gnom.jpg"
  },
  {
    "id": 71,
    "slug": "julian-buchendorfer-tor-von-kiew",
    "name": "Julian Buchendorfer",
    "vorname": "Julian",
    "nachname": "Buchendorfer",
    "jahr": 2006,
    "motif": "tor-von-kiew",
    "motifTitle": "Das große Tor von Kiew",
    "technik": "Farbstifte",
    "titel": "Das große Tor von Kiew",
    "file": "20191101_152244.jpg",
    "image": "/werke/julian-buchendorfer-tor-von-kiew.jpg"
  },
  {
    "id": 72,
    "slug": "darja-bauer-baba-jaga",
    "name": "Darja Bauer",
    "vorname": "Darja",
    "nachname": "Bauer",
    "jahr": 2008,
    "motif": "baba-jaga",
    "motifTitle": "Die Hütte der Baba-Jaga",
    "technik": "Mischtechnik",
    "titel": "",
    "file": "darja_bauer.jpg",
    "image": "/werke/darja-bauer-baba-jaga.jpg"
  },
  {
    "id": 73,
    "slug": "emma-einberger-gnom",
    "name": "Emma Einberger",
    "vorname": "Emma",
    "nachname": "Einberger",
    "jahr": 2008,
    "motif": "gnom",
    "motifTitle": "Der Gnom",
    "technik": "Wasserfarben",
    "titel": "",
    "file": "emma_einberger.jpg",
    "image": "/werke/emma-einberger-gnom.jpg"
  },
  {
    "id": 74,
    "slug": "marie-baumgartner-gnom",
    "name": "Marie Baumgartner",
    "vorname": "Marie",
    "nachname": "Baumgartner",
    "jahr": 2008,
    "motif": "gnom",
    "motifTitle": "Der Gnom",
    "technik": "Ölkreiden",
    "titel": "",
    "file": "marie_baumgartner.JPG",
    "image": "/werke/marie-baumgartner-gnom.jpg"
  },
  {
    "id": 75,
    "slug": "maximilian-paltinger-gnom",
    "name": "Maximilian Paltinger",
    "vorname": "Maximilian",
    "nachname": "Paltinger",
    "jahr": 2008,
    "motif": "gnom",
    "motifTitle": "Der Gnom",
    "technik": "Mischtechnik",
    "titel": "",
    "file": "maximilian_paltinger.jpg",
    "image": "/werke/maximilian-paltinger-gnom.jpg"
  },
  {
    "id": 76,
    "slug": "moritz-rauter-gnom",
    "name": "Moritz Rauter",
    "vorname": "Moritz",
    "nachname": "Rauter",
    "jahr": 2008,
    "motif": "gnom",
    "motifTitle": "Der Gnom",
    "technik": "Mischtechnik",
    "titel": "",
    "file": "moritz_rauter.JPG",
    "image": "/werke/moritz-rauter-gnom.jpg"
  },
  {
    "id": 77,
    "slug": "valentin-stux-gnom",
    "name": "Valentin Stux",
    "vorname": "Valentin",
    "nachname": "Stux",
    "jahr": 2008,
    "motif": "gnom",
    "motifTitle": "Der Gnom",
    "technik": "Mischtechnik",
    "titel": "",
    "file": "valentin_stux.jpg",
    "image": "/werke/valentin-stux-gnom.jpg"
  },
  {
    "id": 78,
    "slug": "tobias-ortmayr-gnom",
    "name": "Tobias Ortmayr",
    "vorname": "Tobias",
    "nachname": "Ortmayr",
    "jahr": 2008,
    "motif": "gnom",
    "motifTitle": "Der Gnom",
    "technik": "Ölkreiden",
    "titel": "",
    "file": "tobias_ortmayr.JPG",
    "image": "/werke/tobias-ortmayr-gnom.jpg"
  },
  {
    "id": 79,
    "slug": "sarah-pfannerer-gnom",
    "name": "Sarah Pfannerer",
    "vorname": "Sarah",
    "nachname": "Pfannerer",
    "jahr": 2008,
    "motif": "gnom",
    "motifTitle": "Der Gnom",
    "technik": "Mischtechnik",
    "titel": "",
    "file": "sarah_pfannerer.JPG",
    "image": "/werke/sarah-pfannerer-gnom.jpg"
  },
  {
    "id": 80,
    "slug": "genoveva-peia-gnom",
    "name": "Genoveva Peia",
    "vorname": "Genoveva",
    "nachname": "Peia",
    "jahr": 2008,
    "motif": "gnom",
    "motifTitle": "Der Gnom",
    "technik": "Mischtechnik",
    "titel": "",
    "file": "genoveva_peia.jpg",
    "image": "/werke/genoveva-peia-gnom.jpg"
  },
  {
    "id": 81,
    "slug": "carla-eckl-gnom",
    "name": "Carla Eckl",
    "vorname": "Carla",
    "nachname": "Eckl",
    "jahr": 2008,
    "motif": "gnom",
    "motifTitle": "Der Gnom",
    "technik": "Mischtechnik",
    "titel": "",
    "file": "carla_eckl.JPG",
    "image": "/werke/carla-eckl-gnom.jpg"
  },
  {
    "id": 82,
    "slug": "anna-kosilek-gnom",
    "name": "Anna Kosilek",
    "vorname": "Anna",
    "nachname": "Kosilek",
    "jahr": 2008,
    "motif": "gnom",
    "motifTitle": "Der Gnom",
    "technik": "Mischtechnik",
    "titel": "",
    "file": "anna_kosilek.jpg",
    "image": "/werke/anna-kosilek-gnom.jpg"
  },
  {
    "id": 83,
    "slug": "elias-lagler-baba-jaga",
    "name": "Elias Lagler",
    "vorname": "Elias",
    "nachname": "Lagler",
    "jahr": 2008,
    "motif": "baba-jaga",
    "motifTitle": "Die Hütte der Baba-Jaga",
    "technik": "Farbstifte",
    "titel": "",
    "file": "elias_lagler.jpg",
    "image": "/werke/elias-lagler-baba-jaga.jpg"
  },
  {
    "id": 84,
    "slug": "paul-rungger-baba-jaga",
    "name": "Paul Rungger",
    "vorname": "Paul",
    "nachname": "Rungger",
    "jahr": 2008,
    "motif": "baba-jaga",
    "motifTitle": "Die Hütte der Baba-Jaga",
    "technik": "Ölkreiden",
    "titel": "",
    "file": "paul_rungger.JPG",
    "image": "/werke/paul-rungger-baba-jaga.jpg"
  },
  {
    "id": 85,
    "slug": "emma-kimmerstorfer-baba-jaga",
    "name": "Emma Kimmerstorfer",
    "vorname": "Emma",
    "nachname": "Kimmerstorfer",
    "jahr": 2008,
    "motif": "baba-jaga",
    "motifTitle": "Die Hütte der Baba-Jaga",
    "technik": "Mischtechnik",
    "titel": "",
    "file": "emma_kimmerstorfer.jpg",
    "image": "/werke/emma-kimmerstorfer-baba-jaga.jpg"
  },
  {
    "id": 86,
    "slug": "helene-aichinger-baba-jaga",
    "name": "Helene Aichinger",
    "vorname": "Helene",
    "nachname": "Aichinger",
    "jahr": 2008,
    "motif": "baba-jaga",
    "motifTitle": "Die Hütte der Baba-Jaga",
    "technik": "Mischtechnik",
    "titel": "",
    "file": "helene_aichinger.jpg",
    "image": "/werke/helene-aichinger-baba-jaga.jpg"
  },
  {
    "id": 87,
    "slug": "sarah-palfi-baba-jaga",
    "name": "Sarah Palfi",
    "vorname": "Sarah",
    "nachname": "Palfi",
    "jahr": 2008,
    "motif": "baba-jaga",
    "motifTitle": "Die Hütte der Baba-Jaga",
    "technik": "Wasserfarben",
    "titel": "",
    "file": "sarah_palfi.JPG",
    "image": "/werke/sarah-palfi-baba-jaga.jpg"
  },
  {
    "id": 88,
    "slug": "tamina-reischl-baba-jaga",
    "name": "Tamina Reischl",
    "vorname": "Tamina",
    "nachname": "Reischl",
    "jahr": 2008,
    "motif": "baba-jaga",
    "motifTitle": "Die Hütte der Baba-Jaga",
    "technik": "Wasserfarben",
    "titel": "",
    "file": "tamina_reischl.JPG",
    "image": "/werke/tamina-reischl-baba-jaga.jpg"
  },
  {
    "id": 89,
    "slug": "katharina-burgstaller-baba-jaga",
    "name": "Katharina Burgstaller",
    "vorname": "Katharina",
    "nachname": "Burgstaller",
    "jahr": 2008,
    "motif": "baba-jaga",
    "motifTitle": "Die Hütte der Baba-Jaga",
    "technik": "Wasserfarben",
    "titel": "",
    "file": "katharina_burgstaller.jpg",
    "image": "/werke/katharina-burgstaller-baba-jaga.jpg"
  },
  {
    "id": 90,
    "slug": "emilia-thalhammer-baba-jaga",
    "name": "Emilia Thalhammer",
    "vorname": "Emilia",
    "nachname": "Thalhammer",
    "jahr": 2008,
    "motif": "baba-jaga",
    "motifTitle": "Die Hütte der Baba-Jaga",
    "technik": "Bleistiftzeichnung",
    "titel": "",
    "file": "emilia_thalhammer.jpg",
    "image": "/werke/emilia-thalhammer-baba-jaga.jpg"
  },
  {
    "id": 91,
    "slug": "aurelia-rogner-baba-jaga",
    "name": "Aurelia Rogner",
    "vorname": "Aurelia",
    "nachname": "Rogner",
    "jahr": 2008,
    "motif": "baba-jaga",
    "motifTitle": "Die Hütte der Baba-Jaga",
    "technik": "Wasserfarben",
    "titel": "",
    "file": "aurelia_rogner.jpg",
    "image": "/werke/aurelia-rogner-baba-jaga.jpg"
  },
  {
    "id": 92,
    "slug": "andreas-hofer-baba-jaga",
    "name": "Andreas Hofer",
    "vorname": "Andreas",
    "nachname": "Hofer",
    "jahr": 2008,
    "motif": "baba-jaga",
    "motifTitle": "Die Hütte der Baba-Jaga",
    "technik": "Wasserfarben",
    "titel": "",
    "file": "andreas_hofer.JPG",
    "image": "/werke/andreas-hofer-baba-jaga.jpg"
  },
  {
    "id": 93,
    "slug": "jakob-weinberger-ochsenkarren",
    "name": "Jakob Weinberger",
    "vorname": "Jakob",
    "nachname": "Weinberger",
    "jahr": 2011,
    "motif": "ochsenkarren",
    "motifTitle": "Der Ochsenkarren",
    "technik": "Buntstifte",
    "titel": "Der Ochsenkarren",
    "file": "IMG_20191030_192242.jpg",
    "image": "/werke/jakob-weinberger-ochsenkarren.jpg"
  },
  {
    "id": 94,
    "slug": "theresa-poell-baba-jaga",
    "name": "Theresa Pöll",
    "vorname": "Theresa",
    "nachname": "Pöll",
    "jahr": 2013,
    "motif": "baba-jaga",
    "motifTitle": "Die Hütte der Baba-Jaga",
    "technik": "Wasserfarben und Filzstifte",
    "titel": "Gruselhaus",
    "file": "IMG_20191016_171301.jpg",
    "image": "/werke/theresa-poell-baba-jaga.jpg"
  },
  {
    "id": 95,
    "slug": "theresa-poell-schloss",
    "name": "Theresa Pöll",
    "vorname": "Theresa",
    "nachname": "Pöll",
    "jahr": 2013,
    "motif": "schloss",
    "motifTitle": "Das alte Schloss",
    "technik": "Wasserfarben",
    "titel": "Altes Schloss mit Wassergraben",
    "file": "IMG_20191016_164545.jpg",
    "image": "/werke/theresa-poell-schloss.jpg"
  },
  {
    "id": 96,
    "slug": "mathias-schablinger-gnom",
    "name": "Mathias Schablinger",
    "vorname": "Mathias",
    "nachname": "Schablinger",
    "jahr": 2006,
    "motif": "gnom",
    "motifTitle": "Der Gnom",
    "technik": "Digital (Zeichenprogramm)",
    "titel": "Der Gnom",
    "file": "IMG_20191028_132208.png",
    "image": "/werke/mathias-schablinger-gnom.jpg"
  },
  {
    "id": 97,
    "slug": "linda-lanza-gnom",
    "name": "Linda Lanza",
    "vorname": "Linda",
    "nachname": "Lanza",
    "jahr": 2008,
    "motif": "gnom",
    "motifTitle": "Der Gnom",
    "technik": "Graphitstifte",
    "titel": "Ein Gnom bei der Gartenarbeit",
    "file": "20191023_124816.jpg",
    "image": "/werke/linda-lanza-gnom.jpg"
  },
  {
    "id": 98,
    "slug": "hubert-schernhammer-schloss",
    "name": "Hubert Schernhammer",
    "vorname": "Hubert",
    "nachname": "Schernhammer",
    "jahr": 2008,
    "motif": "schloss",
    "motifTitle": "Das alte Schloss",
    "technik": "Grafitzeichnung",
    "titel": "Das alte Schloss",
    "file": "15718276986792110442015840309819.jpg",
    "image": "/werke/hubert-schernhammer-schloss.jpg"
  },
  {
    "id": 99,
    "slug": "mika-kaltenberger-schloss",
    "name": "Mika Kaltenberger",
    "vorname": "Mika",
    "nachname": "Kaltenberger",
    "jahr": 2007,
    "motif": "schloss",
    "motifTitle": "Das alte Schloss",
    "technik": "Grafitzeichnung",
    "titel": "Das alte Schloss",
    "file": "15718710322841584571163.jpg",
    "image": "/werke/mika-kaltenberger-schloss.jpg"
  },
  {
    "id": 100,
    "slug": "dillon-rowan-gnom",
    "name": "Dillon Rowan",
    "vorname": "Dillon",
    "nachname": "Rowan",
    "jahr": 2008,
    "motif": "gnom",
    "motifTitle": "Der Gnom",
    "technik": "Graphitstift",
    "titel": "Der Gartengnom",
    "file": "15718278822953273877206374563034.jpg",
    "image": "/werke/dillon-rowan-gnom.jpg"
  },
  {
    "id": 101,
    "slug": "alex-makel-baba-jaga",
    "name": "Alex Makel",
    "vorname": "Alex",
    "nachname": "Makel",
    "jahr": 2006,
    "motif": "baba-jaga",
    "motifTitle": "Die Hütte der Baba-Jaga",
    "technik": "Graphit- und Bleistiftzeichnung",
    "titel": "",
    "file": "1571827133959_1379819582.jpg",
    "image": "/werke/alex-makel-baba-jaga.jpg"
  },
  {
    "id": 102,
    "slug": "elisabeth-hufnagl-baba-jaga",
    "name": "Elisabeth Hufnagl",
    "vorname": "Elisabeth",
    "nachname": "Hufnagl",
    "jahr": 1996,
    "motif": "baba-jaga",
    "motifTitle": "Die Hütte der Baba-Jaga",
    "technik": "Fotografie",
    "titel": "Hütte der Baba-Jaga, gesichtet in Edt bei Lambach",
    "file": "IMG_20190310_WA0003.jpg",
    "image": "/werke/elisabeth-hufnagl-baba-jaga.jpg"
  },
  {
    "id": 103,
    "slug": "poldi-plaimer-limoges",
    "name": "Poldi Plaimer",
    "vorname": "Poldi",
    "nachname": "Plaimer",
    "jahr": 1950,
    "motif": "limoges",
    "motifTitle": "Limoges. Der Marktplatz",
    "technik": "Acryl, Aquarell",
    "titel": "7. Strömung",
    "file": "7.STRÖMUNG___ACRYL____40_x_50_cm.._Collage__teilweise_gepachtelt.jpg",
    "image": "/werke/poldi-plaimer-limoges.jpg"
  },
  {
    "id": 104,
    "slug": "poldi-plaimer-katakomben",
    "name": "Poldi Plaimer",
    "vorname": "Poldi",
    "nachname": "Plaimer",
    "jahr": 1950,
    "motif": "katakomben",
    "motifTitle": "Die Katakomben",
    "technik": "Acryl, Collage",
    "titel": "9. Mondlicht",
    "file": "9.MONDLICHT_1___ACRYL___40_x50_cm.._Collage_mit_Struktur_und__Spiegeln.jpg",
    "image": "/werke/poldi-plaimer-katakomben.jpg"
  },
  {
    "id": 105,
    "slug": "poldi-plaimer-katakomben-2",
    "name": "Poldi Plaimer",
    "vorname": "Poldi",
    "nachname": "Plaimer",
    "jahr": 1959,
    "motif": "katakomben",
    "motifTitle": "Die Katakomben",
    "technik": "Acryl",
    "titel": "33. Sommerwind",
    "file": "33._SOMMERWIND___ACRYL____40_x50_cm..Diagonale_gespachtelt.jpg",
    "image": "/werke/poldi-plaimer-katakomben-2.jpg"
  },
  {
    "id": 106,
    "slug": "poldi-plaimer-kuechlein",
    "name": "Poldi Plaimer",
    "vorname": "Poldi",
    "nachname": "Plaimer",
    "jahr": 1950,
    "motif": "kuechlein",
    "motifTitle": "Ballett der Küchlein",
    "technik": "Aquarell",
    "titel": "34. Sonnengold",
    "file": "34.SONNENGOLD_1___ACRYL___40_x50_cm__Collage_mit_Sruktur_und_Spiegeln.jpg",
    "image": "/werke/poldi-plaimer-kuechlein.jpg"
  },
  {
    "id": 107,
    "slug": "poldi-plaimer-limoges-2",
    "name": "Poldi Plaimer",
    "vorname": "Poldi",
    "nachname": "Plaimer",
    "jahr": 1950,
    "motif": "limoges",
    "motifTitle": "Limoges. Der Marktplatz",
    "technik": "Acryl",
    "titel": "65. Glaube Hoffnung Liebe",
    "file": "65._GLAUBE_HOFFNUNG_LIEBE.jpg",
    "image": "/werke/poldi-plaimer-limoges-2.jpg"
  },
  {
    "id": 108,
    "slug": "valentina-oeller-gnom",
    "name": "Valentina Öller",
    "vorname": "Valentina",
    "nachname": "Öller",
    "jahr": 2011,
    "motif": "gnom",
    "motifTitle": "Der Gnom",
    "technik": "Filzstift",
    "titel": "Die Rocker-Katze",
    "file": "D9C719AA_46A9_4370_B89C_24D1C76A0841.jpeg",
    "image": "/werke/valentina-oeller-gnom.jpg"
  },
  {
    "id": 109,
    "slug": "emilia-brandner-tuilerien",
    "name": "Emilia Brandner",
    "vorname": "Emilia",
    "nachname": "Brandner",
    "jahr": 2001,
    "motif": "tuilerien",
    "motifTitle": "Die Tuilerien",
    "technik": "Holzstifte",
    "titel": "Geschmolzen",
    "file": "15699424994861493660745.jpg",
    "image": "/werke/emilia-brandner-tuilerien.jpg"
  },
  {
    "id": 110,
    "slug": "franz-hochreiter-ochsenkarren",
    "name": "Franz Hochreiter",
    "vorname": "Franz",
    "nachname": "Hochreiter",
    "jahr": 1959,
    "motif": "ochsenkarren",
    "motifTitle": "Der Ochsenkarren",
    "technik": "Acryl auf Papier",
    "titel": "Ochsen-Tor",
    "file": "Malerei_Großformat_13_14_010.JPG",
    "image": "/werke/franz-hochreiter-ochsenkarren.jpg"
  },
  {
    "id": 111,
    "slug": "franz-hochreiter-baba-jaga",
    "name": "Franz Hochreiter",
    "vorname": "Franz",
    "nachname": "Hochreiter",
    "jahr": 1959,
    "motif": "baba-jaga",
    "motifTitle": "Die Hütte der Baba-Jaga",
    "technik": "Acryl auf Leinwand",
    "titel": "Baba-Jaga",
    "file": "1.JPG",
    "image": "/werke/franz-hochreiter-baba-jaga.jpg"
  },
  {
    "id": 112,
    "slug": "franz-hochreiter-tote-sprache",
    "name": "Franz Hochreiter",
    "vorname": "Franz",
    "nachname": "Hochreiter",
    "jahr": 1959,
    "motif": "tote-sprache",
    "motifTitle": "Mit den Toten in einer toten Sprache",
    "technik": "Acryl auf Karton",
    "titel": "Am „Runden Tisch“",
    "file": "7.JPG",
    "image": "/werke/franz-hochreiter-tote-sprache.jpg"
  },
  {
    "id": 113,
    "slug": "franz-hochreiter-schloss",
    "name": "Franz Hochreiter",
    "vorname": "Franz",
    "nachname": "Hochreiter",
    "jahr": 1959,
    "motif": "schloss",
    "motifTitle": "Das alte Schloss",
    "technik": "Acryl auf Leinwand",
    "titel": "Nach Zwölf",
    "file": "3.JPG",
    "image": "/werke/franz-hochreiter-schloss.jpg"
  },
  {
    "id": 114,
    "slug": "franz-hochreiter-tuilerien",
    "name": "Franz Hochreiter",
    "vorname": "Franz",
    "nachname": "Hochreiter",
    "jahr": 1959,
    "motif": "tuilerien",
    "motifTitle": "Die Tuilerien",
    "technik": "Acryl auf Papier",
    "titel": "Das mache ich spielend",
    "file": "Malerei_Großformat_13_14_008.JPG",
    "image": "/werke/franz-hochreiter-tuilerien.jpg"
  },
  {
    "id": 115,
    "slug": "franz-hochreiter-gnom",
    "name": "Franz Hochreiter",
    "vorname": "Franz",
    "nachname": "Hochreiter",
    "jahr": 1959,
    "motif": "gnom",
    "motifTitle": "Der Gnom",
    "technik": "Acryl auf Leinwand",
    "titel": "Der Gnom",
    "file": "2.JPG",
    "image": "/werke/franz-hochreiter-gnom.jpg"
  },
  {
    "id": 116,
    "slug": "maximilian-und-valentin-huber-katakomben",
    "name": "Maximilian und Valentin Huber",
    "vorname": "Maximilian und Valentin",
    "nachname": "Huber",
    "jahr": 2015,
    "motif": "katakomben",
    "motifTitle": "Die Katakomben",
    "technik": "Acrylfarbe mit Fingern",
    "titel": "Sturm",
    "file": "DSC_1545.JPG",
    "image": "/werke/maximilian-und-valentin-huber-katakomben.jpg"
  },
  {
    "id": 117,
    "slug": "johann-mayrhofer-tor-von-kiew",
    "name": "Johann Mayrhofer",
    "vorname": "Johann",
    "nachname": "Mayrhofer",
    "jahr": 2013,
    "motif": "tor-von-kiew",
    "motifTitle": "Das große Tor von Kiew",
    "technik": "Farbstift mit Wasser",
    "titel": "",
    "file": "p20033681_18.09.2019___002_.pdf",
    "image": "/werke/johann-mayrhofer-tor-von-kiew.jpg"
  },
  {
    "id": 118,
    "slug": "sarah-poltschak-schloss",
    "name": "Sarah Poltschak",
    "vorname": "Sarah",
    "nachname": "Poltschak",
    "jahr": 2013,
    "motif": "schloss",
    "motifTitle": "Das alte Schloss",
    "technik": "Farbstift auf Papier",
    "titel": "Das alte Schloss",
    "file": "Das_alte_Schloss.pdf",
    "image": "/werke/sarah-poltschak-schloss.jpg"
  },
  {
    "id": 119,
    "slug": "emil-jakob-guttmann-baba-jaga",
    "name": "Emil Jakob Guttmann",
    "vorname": "Emil Jakob",
    "nachname": "Guttmann",
    "jahr": 2016,
    "motif": "baba-jaga",
    "motifTitle": "Die Hütte der Baba-Jaga",
    "technik": "Aquarell",
    "titel": "Ein spannender Morgen",
    "file": "Emil_Jakob_Guttmann.jpg",
    "image": "/werke/emil-jakob-guttmann-baba-jaga.jpg"
  },
  {
    "id": 120,
    "slug": "anja-rosenauer-tote-sprache",
    "name": "Anja Rosenauer",
    "vorname": "Anja",
    "nachname": "Rosenauer",
    "jahr": 2001,
    "motif": "tote-sprache",
    "motifTitle": "Mit den Toten in einer toten Sprache",
    "technik": "Digital",
    "titel": "",
    "file": "Screenshot_20170608_213342.png",
    "image": "/werke/anja-rosenauer-tote-sprache.jpg"
  },
  {
    "id": 121,
    "slug": "sebastian-poltschak-schloss",
    "name": "Sebastian Poltschak",
    "vorname": "Sebastian",
    "nachname": "Poltschak",
    "jahr": 1988,
    "motif": "schloss",
    "motifTitle": "Das alte Schloss",
    "technik": "Fotografie",
    "titel": "Ente in New York",
    "file": "Ente.jpg",
    "image": "/werke/sebastian-poltschak-schloss.jpg"
  }
];
